トップページの見た目を綺麗にする
koheinoguchi0216/heroku_practice pull request #26
Opened 2021-05-18 12:32 UTC by koheinoguchi0216

トップページを編集しました！herokuへデプロイ済みです！
画像が上手く表示できません、、
CSSファイルに結構コードを追加してしまったのですが、段落ごとにPR作った方が良かったでしょうか？
<img width="1440" alt="スクリーンショット 2021-05-18 21 28 11" src="https://user-images.githubusercontent.com/76785015/118651373-71a47680-b820-11eb-9abd-cdcef03af7b4.png">

<img width="1440" alt="スクリーンショット 2021-05-18 21 28 35" src="https://user-images.githubusercontent.com/76785015/118651331-64878780-b820-11eb-9623-85bb8bd4d80b.png">

2021-05-18 15:34 UTC, youhei19880130 commented
> 段落ごとにPR作った方が良かったでしょうか？

その必要はないから、今回のような感じで良いと思う！

2021-05-18 15:39 UTC, youhei19880130 commented
@koheinoguchi0216 
ベースのスタイルはbootstrapとか使うと楽ちんだよ！
SP／PCともに最適化してくれるし！
https://admin-it.xyz/python/how-to-use-flask-bootstrap/

2021-05-18 15:43 UTC, youhei19880130 requested changes
@koheinoguchi0216 
コメントしましたー！

2021-05-18 15:43 UTC, youhei19880130 commented on templates/home.html
> +          <img class="logo" src="../img/anpanman_log.jpeg" alt="アンパンマンのロゴ画像">
画像表示はこれを参考にしたら？
https://www.nblog09.com/w/2020/12/24/flask_url_for/

ちなみに、相対パスはやめたほうが良い！

2021-05-19 02:40 UTC, koheinoguchi0216 commented on templates/home.html
> +          <img class="logo" src="../img/anpanman_log.jpeg" alt="アンパンマンのロゴ画像">
@youhei19880130 
url_forという書き方があるんですね！パス書く時は絶対パスで書きます！

2021-05-19 02:41 UTC, koheinoguchi0216 commented
@youhei19880130 
コメント確認しました！このPRは閉じてbootstrapで作り直した方が良いですか？

2021-05-19 02:43 UTC, youhei19880130 commented
@koheinoguchi0216 
bootstrapは今は気にせずコメントしたところをなおそう！

2021-05-20 01:46 UTC, koheinoguchi0216 commented on templates/home.html
> +          <img class="logo" src="../img/anpanman_log.jpeg" alt="アンパンマンのロゴ画像">
https://github.com/koheinoguchi0216/heroku_practice/blob/559394f22be10e48d2575c13d86ce26b958ad835/templates/home.html#L18

@youhei19880130
既にurl_forを使ってコード書いてました、、
上のリプライで初見ですみたいなコメントしてて恥ずかしいです、、

2021-05-20 02:00 UTC, koheinoguchi0216 commented
@youhei19880130 
url_forを使って画像を表示しました！

url_forはstaticフォルダ内のファイルを見にいくと記事に書いてあったので、
表示させたい画像ファイルをstaticフォルダに追加しています！

<img width="1440" alt="スクリーンショット 2021-05-20 10 56 25" src="https://user-images.githubusercontent.com/76785015/118907375-605f8500-b95a-11eb-9619-3472f7f76ba1.png">
<img width="1440" alt="スクリーンショット 2021-05-20 10 55 18" src="https://user-images.githubusercontent.com/76785015/118907398-6b1a1a00-b95a-11eb-9bcb-a150289da642.png">

2021-05-20 12:57 UTC, youhei19880130 reviewed
@koheinoguchi0216 コメントしましたー

2021-05-20 12:57 UTC, youhei19880130 commented on app.py
> +    filename = ['anpanman-logo.jpeg','anpanman.jpg']
ここではわざわざ配列作らなくてよいんじゃない？

2021-05-20 12:57 UTC, youhei19880130 commented on templates/home.html
> +          <img src="{{url_for('static', filename=file[0])}}" width="200px" height="165px">
filenameは直接テキストでもいいんじゃない？

2021-05-22 05:03 UTC, koheinoguchi0216 commented
@youhei19880130
画像を絶対パスで指定して表示させたいのですがキャプチャのような結果になりました。
絶対パスの書き方を教えて欲しいです！


<img width="1440" alt="スクリーンショット 2021-05-22 13 56 58" src="https://user-images.githubusercontent.com/76785015/119215071-4fec0d80-bb06-11eb-9b0e-0f05e20bdd83.png">


<img width="1440" alt="スクリーンショット 2021-05-22 13 57 25" src="https://user-images.githubusercontent.com/76785015/119215077-57131b80-bb06-11eb-8e0d-b4ca7cfa7e76.png">

2021-05-22 12:23 UTC, koheinoguchi0216 commented on templates/home.html
> +          <img src="{{url_for('static', filename='anpanman-logo.jpeg')}}" width="200px" height="165px">
画像ファイル名間違っていました、、
filenameの値は絶対パスでなくて良いんですね！

2021-05-22 12:26 UTC, koheinoguchi0216 commented on templates/home.html
> +        <img src="{{url_for('static', filename='anpanman.jpg')}}" width="300px" height="340px">
画像ファイルの拡張子間違えていました、、

2021-05-22 12:27 UTC, youhei19880130 commented on templates/home.html
> +          <img src="{{url_for('static', filename='anpanman-logo.jpeg')}}" width="200px" height="165px">
@koheinoguchi0216
url_forのドキュメントをちゃんと読むのだー！！

2021-05-22 12:53 UTC, koheinoguchi0216 commented on templates/home.html
> +          <img src="{{url_for('static', filename='anpanman-logo.jpeg')}}" width="200px" height="165px">
@youhei19880130
url_forはデフォルトでstaticを見にいくからファイル名だけで大丈夫でした、、

2021-05-23 10:02 UTC, youhei19880130 approved these changes
これで問題なければmergeしちゃおう！

2021-05-23 10:45 UTC, merged