APIを使って画像を取得し表示する
koheinoguchi0216/heroku_practice pull request #27
Opened 2021-05-25 11:28 UTC by koheinoguchi0216

qiitaの記事を参考に画像取得用ファイル（google_api.py）を作成しました！

2021-05-25 11:46 UTC, koheinoguchi0216 commented
@youhei19880130
「あんぱんまん」で画像検索して画像を取得しました！

2021-05-25 11:50 UTC, youhei19880130 commented
@koheinoguchi0216 
色々と画像ファイル増えているけど、それぞれ何？

2021-05-25 12:12 UTC, koheinoguchi0216 commented
@youhei19880130
それぞれアンパンマンの画像がimgsフォルダに格納されてます！
<img width="1440" alt="スクリーンショット 2021-05-25 20 55 22" src="https://user-images.githubusercontent.com/76785015/119495790-bdfe3200-bd9d-11eb-9e18-08e83b7c34c7.png">

2021-05-25 12:13 UTC, youhei19880130 commented
格納じゃなくて、表示しよう！もう一枚ページ作って。
@koheinoguchi0216

2021-05-25 12:19 UTC, koheinoguchi0216 commented
@youhei19880130
了解しました！新しくhtmlファイルを作ってそこに表示させるという認識で合ってますか？

2021-05-25 14:50 UTC, youhei19880130 commented
@koheinoguchi0216 
YES!!

2021-05-29 05:56 UTC, koheinoguchi0216 commented
@youhei19880130 
新しく作ったHTMLファイルに画像を表示させました！
`google_api.py`の不要な行削除しました！
herokuデプロイ済みです！
<img width="1440" alt="スクリーンショット 2021-05-29 14 43 46" src="https://user-images.githubusercontent.com/76785015/120059665-dae08100-c08d-11eb-940b-d3f75946ed4e.png">
<img width="1440" alt="スクリーンショット 2021-05-29 14 43 56" src="https://user-images.githubusercontent.com/76785015/120059670-dcaa4480-c08d-11eb-9b8b-e0e0c8df1e2c.png">

2021-06-01 02:58 UTC, youhei19880130 requested changes
@koheinoguchi0216 
画像とか不要なファイルがいくつかありそうだけど、どうかな？
あと、appが動いてないよー　＠へろく
<img width="1679" alt="Screen Shot 2021-06-01 at 11 57 13" src="https://user-images.githubusercontent.com/7796505/120260334-a6103c00-c2d0-11eb-98b5-aa69beb5ada4.png">

2021-06-01 02:58 UTC, youhei19880130 commented on static/corr_table/corr_table.json
> +{"https://images-na.ssl-images-amazon.com/images/I/91+H2RtCSIL.jpg": "0a0b4ac295febecec3071bc0d302639899f47517cbc2ed7427cf545121e35492", "https://www.bandai.co.jp/images/character/anpanman/img_keyvis
このファイルは何？

2021-06-01 11:22 UTC, koheinoguchi0216 commented on static/corr_table/corr_table.json
> +{"https://images-na.ssl-images-amazon.com/images/I/91+H2RtCSIL.jpg": "0a0b4ac295febecec3071bc0d302639899f47517cbc2ed7427cf545121e35492", "https://www.bandai.co.jp/images/character/anpanman/img_keyvis
@youhei19880130
APIで取得した画像のURLです！データとして書き出す必要はないので削除します！

2021-06-01 11:22 UTC, koheinoguchi0216 commented
@youhei19880130
不要な画像とファイルを削除しました！

2021-06-01 12:01 UTC, youhei19880130 approved these changes
よさそう！

2021-06-01 12:01 UTC, youhei19880130 commented on app.py
> +    # sakki no method!!
このコメントアウトは不要でしょ！

2021-06-02 03:54 UTC, merged